# Generated by Django 4.0.6 on 2022-08-31 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='administrator',
            name='username',
            field=models.CharField(blank=True, max_length=100, unique=True),
        ),
    ]
