# Generated by Django 4.0.6 on 2022-11-24 12:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin', '0002_alter_administrator_username'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Administrator',
        ),
    ]
