# Generated by Django 4.0.6 on 2022-11-29 06:30

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('association', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Intervenantfieldschool',
            fields=[
                ('id', models.IntegerField(blank=True, primary_key=True, serialize=False)),
                ('intervenant', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'intervenantfieldschool',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('title_en', models.CharField(blank=True, max_length=255, null=True)),
                ('title_fr', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('description_en', models.TextField(blank=True, null=True)),
                ('description_fr', models.TextField(blank=True, null=True)),
                ('date', models.DateField(blank=True, default=datetime.datetime(2022, 11, 29, 6, 30, 33, 744515, tzinfo=utc), null=True)),
                ('note', models.CharField(blank=True, max_length=255, null=True)),
                ('note_en', models.CharField(blank=True, max_length=255, null=True)),
                ('note_fr', models.CharField(blank=True, max_length=255, null=True)),
                ('slug', models.SlugField(allow_unicode=True,blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'activity',
            },
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('latitude', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'location',
            },
        ),
        migrations.CreateModel(
            name='Typeactivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(blank=True, max_length=150, null=True, unique=True)),
                ('type_en', models.CharField(blank=True, max_length=150, null=True, unique=True)),
                ('type_fr', models.CharField(blank=True, max_length=150, null=True, unique=True)),
            ],
            options={
                'db_table': 'typeactivity',
            },
        ),
        migrations.CreateModel(
            name='Visit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dateend', models.DateField(blank=True, null=True)),
                ('idactivity', models.ForeignKey(db_column='idactivity', on_delete=django.db.models.deletion.CASCADE, to='activities.activity')),
                ('idlocation', models.ForeignKey(db_column='idlocation', on_delete=django.db.models.deletion.CASCADE, to='activities.location')),
            ],
            options={
                'db_table': 'visit',
            },
        ),
        migrations.CreateModel(
            name='Typesubactivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(blank=True, max_length=150, null=True, unique=True)),
                ('type_en', models.CharField(blank=True, max_length=150, null=True, unique=True)),
                ('type_fr', models.CharField(blank=True, max_length=150, null=True, unique=True)),
                ('idtypeactivity', models.ForeignKey(db_column='idtypeactivity', on_delete=django.db.models.deletion.CASCADE, to='activities.typeactivity')),
            ],
            options={
                'db_table': 'typesubactivity',
            },
        ),
        migrations.CreateModel(
            name='Fieldschool',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('iddept', models.ForeignKey(blank=True, db_column='iddept', null=True, on_delete=django.db.models.deletion.CASCADE, to='association.department')),
                ('idinst', models.ForeignKey(db_column='idinst', on_delete=django.db.models.deletion.CASCADE, to='association.institution')),
                ('idvisit', models.ForeignKey(db_column='idvisit', on_delete=django.db.models.deletion.CASCADE, to='activities.visit')),
            ],
            options={
                'db_table': 'fieldschool',
            },
        ),
        migrations.CreateModel(
            name='Activityperson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idactivity', models.ForeignKey(db_column='idactivity', on_delete=django.db.models.deletion.CASCADE, to='activities.activity')),
                ('idperson', models.ForeignKey(db_column='idperson', on_delete=django.db.models.deletion.CASCADE, to='association.person')),
            ],
            options={
                'db_table': 'activityperson',
            },
        ),
        migrations.CreateModel(
            name='Activityinstitution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idactivity', models.ForeignKey(db_column='idactivity', on_delete=django.db.models.deletion.CASCADE, to='activities.activity')),
                ('idinst', models.ForeignKey(db_column='idinst', on_delete=django.db.models.deletion.CASCADE, to='association.institution')),
            ],
            options={
                'db_table': 'activityinstitution',
            },
        ),
        migrations.CreateModel(
            name='Activityimage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.CharField(blank=True, max_length=255, null=True)),
                ('idactivity', models.ForeignKey(db_column='idactivity', on_delete=django.db.models.deletion.CASCADE, to='activities.activity')),
            ],
            options={
                'db_table': 'activityimage',
            },
        ),
        migrations.AddField(
            model_name='activity',
            name='idtypeactivity',
            field=models.ForeignKey(db_column='idtypeactivity', on_delete=django.db.models.deletion.CASCADE, to='activities.typeactivity'),
        ),
        migrations.AddField(
            model_name='activity',
            name='idtypesubactivity',
            field=models.ForeignKey(db_column='idtypesubactivity', null=True, on_delete=django.db.models.deletion.CASCADE, to='activities.typesubactivity'),
        ),
        migrations.AddField(
            model_name='visit',
            name='idtypesubactivity',
            field=models.ForeignKey(db_column='idtypesubactivity', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='activities.typesubactivity'),
        ),
    ]
