# Generated by Django 4.0.6 on 2022-08-30 09:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='activityimage',
            options={},
        ),
    ]
