# Generated by Django 4.0.6 on 2022-09-22 14:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0002_remove_activityimage_idimage_activityimage_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activityimage',
            name='idactivity',
            field=models.ForeignKey(db_column='idactivity', on_delete=django.db.models.deletion.CASCADE, to='activities.activity'),
        ),
        migrations.AlterField(
            model_name='activityinstitution',
            name='idactivity',
            field=models.ForeignKey(db_column='idactivity', on_delete=django.db.models.deletion.CASCADE, to='activities.activity'),
        ),
        migrations.AlterField(
            model_name='activityperson',
            name='idactivity',
            field=models.ForeignKey(db_column='idactivity', on_delete=django.db.models.deletion.CASCADE, to='activities.activity'),
        ),
        migrations.AlterField(
            model_name='fieldschool',
            name='idvisit',
            field=models.ForeignKey(db_column='idvisit', on_delete=django.db.models.deletion.CASCADE, to='activities.visit'),
        ),
        migrations.AlterField(
            model_name='visit',
            name='idactivity',
            field=models.ForeignKey(db_column='idactivity', on_delete=django.db.models.deletion.CASCADE, to='activities.activity'),
        ),
    ]
