# Generated by Django 4.0.6 on 2022-11-29 06:49

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0003_alter_activity_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='date',
            field=models.DateField(blank=True, default=datetime.datetime(2022, 11, 29, 6, 49, 55, 498077, tzinfo=utc), null=True),
        ),
    ]
