# Generated by Django 4.0.6 on 2022-10-11 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0003_alter_activityimage_idactivity_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='typeactivity',
            name='type',
            field=models.CharField(blank=True, max_length=150, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='typesubactivity',
            name='type',
            field=models.CharField(blank=True, max_length=150, null=True, unique=True),
        ),
    ]
