# Generated by Django 4.0.6 on 2022-12-01 06:51

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0004_alter_activity_date'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Intervenantfieldschool',
        ),
        migrations.AlterField(
            model_name='activity',
            name='date',
            field=models.DateField(blank=True, default=datetime.datetime(2022, 12, 1, 6, 51, 24, 464175, tzinfo=utc), null=True),
        ),
    ]
