# Generated by Django 4.0.6 on 2022-10-12 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0004_alter_typeactivity_type_alter_typesubactivity_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, null=True),
        ),
    ]
