# Generated by Django 4.0.6 on 2022-10-17 07:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0005_activity_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idactivity', models.ForeignKey(db_column='idactivity', on_delete=django.db.models.deletion.CASCADE, to='activities.activity')),
                ('idtypesubactivity', models.ForeignKey(db_column='idtypesubactivity', on_delete=django.db.models.deletion.DO_NOTHING, to='activities.typesubactivity')),
            ],
            options={
                'db_table': 'subactivity',
            },
        ),
    ]
