# Generated by Django 4.0.6 on 2022-10-17 07:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0006_subactivity'),
    ]

    operations = [
        migrations.AddField(
            model_name='visit',
            name='idsubactivity',
            field=models.ForeignKey(db_column='idsubactivity', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='activities.subactivity'),
        ),
    ]
