# Generated by Django 4.0.6 on 2022-10-17 08:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0007_visit_idsubactivity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='visit',
            name='idsubactivity',
        ),
        migrations.AddField(
            model_name='activity',
            name='idtypesubactivity',
            field=models.ForeignKey(db_column='idtypesubactivity', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='activities.typesubactivity'),
        ),
        migrations.DeleteModel(
            name='SubActivity',
        ),
    ]
