# Generated by Django 4.0.6 on 2022-10-18 07:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0008_remove_visit_idsubactivity_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='visit',
            name='idtypesubactivity',
        ),
    ]
