# Generated by Django 4.0.6 on 2022-10-26 08:53

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0010_alter_activity_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='date',
            field=models.DateField(blank=True, default=datetime.datetime(2022, 10, 26, 8, 53, 52, 495672, tzinfo=utc), null=True),
        ),
    ]
