# Generated by Django 4.0.6 on 2022-10-27 07:07

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0017_alter_activity_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='date',
            field=models.DateField(blank=True, default=datetime.datetime(2022, 10, 27, 7, 7, 54, 997459, tzinfo=utc), null=True),
        ),
    ]
