# Generated by Django 4.0.6 on 2022-10-27 11:26

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0018_activity_description_en_activity_description_fr_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='date',
            field=models.DateField(blank=True, default=datetime.datetime(2022, 10, 27, 11, 26, 32, 962401, tzinfo=utc), null=True),
        ),
    ]
