# Generated by Django 4.0.6 on 2022-10-27 13:03

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0019_alter_activity_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activity',
            name='slug_en',
        ),
        migrations.RemoveField(
            model_name='activity',
            name='slug_fr',
        ),
        migrations.AlterField(
            model_name='activity',
            name='date',
            field=models.DateField(blank=True, default=datetime.datetime(2022, 10, 27, 13, 3, 47, 838852, tzinfo=utc), null=True),
        ),
    ]
