# Generated by Django 4.0.6 on 2022-10-31 11:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0020_remove_activity_slug_en_remove_activity_slug_fr_and_more'),
    ]

