# Generated by Django 4.0.6 on 2022-10-31 11:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0021_auto_20221031_1434'),
    ]

    operations = [
    ]
