# Generated by Django 4.0.6 on 2022-11-02 05:51

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0022_auto_20221031_1446'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='date',
            field=models.DateField(blank=True, default=datetime.datetime(2022, 11, 2, 5, 51, 21, 859085, tzinfo=utc), null=True),
        ),
        migrations.AlterField(
            model_name='activity',
            name='idtypeactivity',
            field=models.ForeignKey(db_column='idtypeactivity', on_delete=django.db.models.deletion.CASCADE, to='activities.typeactivity'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='idtypesubactivity',
            field=models.ForeignKey(db_column='idtypesubactivity', null=True, on_delete=django.db.models.deletion.CASCADE, to='activities.typesubactivity'),
        ),
        migrations.AlterField(
            model_name='visit',
            name='idlocation',
            field=models.ForeignKey(db_column='idlocation', on_delete=django.db.models.deletion.CASCADE, to='activities.location'),
        ),
    ]
