# Generated by Django 4.2.1 on 2023-11-07 17:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0023_alter_activity_date_alter_activity_idtypeactivity_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='visit',
            name='idtypesubactivity',
        ),
        migrations.AlterField(
            model_name='activity',
            name='date',
            field=models.DateField(blank=True, default=datetime.datetime(2023, 11, 7, 17, 37, 2, 595270, tzinfo=datetime.timezone.utc), null=True),
        ),
        migrations.AlterField(
            model_name='activity',
            name='slug',
            field=models.SlugField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
