# Generated by Django 4.0.6 on 2022-11-02 19:17

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0023_alter_activity_date_alter_activity_idtypeactivity_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='date',
            field=models.DateField(blank=True, default=datetime.datetime(2022, 11, 2, 19, 17, 5, 142072, tzinfo=utc), null=True),
        ),
    ]
