# Generated by Django 4.0.6 on 2022-11-03 06:00

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0024_alter_activity_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='date',
            field=models.DateField(blank=True, default=datetime.datetime(2022, 11, 3, 6, 0, 52, 43245, tzinfo=utc), null=True),
        ),
    ]
