# Generated by Django 4.2.1 on 2023-11-07 17:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0024_remove_visit_idtypesubactivity_alter_activity_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='date',
            field=models.DateField(blank=True, default=datetime.datetime(2023, 11, 7, 17, 46, 54, 552928, tzinfo=datetime.timezone.utc), null=True),
        ),
    ]
