# Generated by Django 4.0.6 on 2022-11-10 07:56

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0025_alter_activity_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='date',
            field=models.DateField(blank=True, default=datetime.datetime(2022, 11, 10, 7, 56, 32, 405829, tzinfo=utc), null=True),
        ),
    ]
