# Generated by Django 4.0.6 on 2022-07-27 07:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Memberviewposts',
            fields=[
                ('id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, max_length=10, null=True, verbose_name='title')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('username', models.CharField(blank=True, max_length=200, null=True)),
                ('description', models.TextField(blank=True, null=True, verbose_name='description')),
                ('mail', models.CharField(blank=True, max_length=100, null=True)),
                ('posts', models.TextField(blank=True, null=True, verbose_name='posts')),
                ('idtypemember', models.IntegerField(blank=True, null=True)),
                ('range', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'memberviewposts',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Degree',
            fields=[
                ('id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'degree',
            },
        ),
        migrations.CreateModel(
            name='Institution',
            fields=[
                ('id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'institution',
            },
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('username', models.CharField(blank=True, max_length=200, null=True)),
                ('mail', models.CharField(blank=True, max_length=100, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('image', models.CharField(blank=True, max_length=255, null=True)),
                ('title', models.CharField(blank=True, max_length=10, null=True)),
                ('range', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'member',
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'post',
            },
        ),
        migrations.CreateModel(
            name='Typemember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('image', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'typemember',
            },
        ),
        migrations.CreateModel(
            name='Studentdegree',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('iddegree', models.ForeignKey(blank=True, db_column='iddegree', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='association.degree')),
                ('idmember', models.ForeignKey(blank=True, db_column='idmember', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='association.member')),
            ],
            options={
                'db_table': 'studentdegree',
            },
        ),
        migrations.CreateModel(
            name='Messageofyear',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('idmember', models.ForeignKey(blank=True, db_column='idmember', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='association.member')),
            ],
            options={
                'db_table': 'messageofyear',
            },
        ),
        migrations.CreateModel(
            name='Memberpostinst',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idinst', models.ForeignKey(blank=True, db_column='idinst', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='association.institution')),
                ('idmember', models.ForeignKey(db_column='idmember', on_delete=django.db.models.deletion.DO_NOTHING, to='association.member')),
                ('idpost', models.ForeignKey(blank=True, db_column='idpost', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='association.post')),
            ],
            options={
                'db_table': 'memberpostinst',
            },
        ),
        migrations.AddField(
            model_name='member',
            name='idtypemember',
            field=models.ForeignKey(db_column='idtypemember', on_delete=django.db.models.deletion.DO_NOTHING, to='association.typemember'),
        ),
    ]
