# Generated by Django 4.0.6 on 2022-11-29 06:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'department',
            },
        ),
        migrations.CreateModel(
            name='Imagetype',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(blank=True, max_length=100, null=True)),
                ('type_en', models.CharField(blank=True, max_length=100, null=True)),
                ('type_fr', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'imagetype',
            },
        ),
        migrations.CreateModel(
            name='Institution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'institution',
            },
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mail', models.CharField(blank=True, max_length=100, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('description_en', models.TextField(blank=True, null=True)),
                ('description_fr', models.TextField(blank=True, null=True)),
                ('image', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'member',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('username', models.CharField(blank=True, max_length=200, null=True)),
                ('title', models.CharField(blank=True, max_length=10, null=True)),
            ],
            options={
                'db_table': 'person',
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('name_en', models.CharField(blank=True, max_length=100, null=True)),
                ('name_fr', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'post',
            },
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=100, null=True)),
                ('pdf', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('year', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'report',
            },
        ),
        migrations.CreateModel(
            name='Typemember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('type_en', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('type_fr', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('description_en', models.TextField(blank=True, null=True)),
                ('description_fr', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'typemember',
            },
        ),
        migrations.CreateModel(
            name='Typememberimage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.CharField(blank=True, max_length=255, null=True)),
                ('idtypemember', models.ForeignKey(db_column='idtypemember', on_delete=django.db.models.deletion.CASCADE, to='association.typemember')),
            ],
            options={
                'db_table': 'typememberimage',
            },
        ),
        migrations.CreateModel(
            name='Partner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True, null=True)),
                ('description_en', models.TextField(blank=True, null=True)),
                ('description_fr', models.TextField(blank=True, null=True)),
                ('link', models.CharField(blank=True, max_length=150, null=True)),
                ('logo', models.CharField(blank=True, max_length=150, null=True)),
                ('isLink', models.BooleanField(default=False)),
                ('idinst', models.ForeignKey(db_column='idinst', on_delete=django.db.models.deletion.CASCADE, to='association.institution')),
            ],
            options={
                'db_table': 'partner',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Messageofyear',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('description_en', models.TextField(blank=True, null=True)),
                ('description_fr', models.TextField(blank=True, null=True)),
                ('idmember', models.ForeignKey(blank=True, db_column='idmember', null=True, on_delete=django.db.models.deletion.CASCADE, to='association.member')),
            ],
            options={
                'db_table': 'messageofyear',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Memberpostinst',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('iddept', models.ForeignKey(blank=True, db_column='iddept', null=True, on_delete=django.db.models.deletion.CASCADE, to='association.department')),
                ('idinst', models.ForeignKey(blank=True, db_column='idinst', null=True, on_delete=django.db.models.deletion.CASCADE, to='association.institution')),
                ('idmember', models.ForeignKey(db_column='idmember', on_delete=django.db.models.deletion.CASCADE, to='association.member')),
                ('idpost', models.ForeignKey(blank=True, db_column='idpost', null=True, on_delete=django.db.models.deletion.CASCADE, to='association.post')),
            ],
            options={
                'db_table': 'memberpostinst',
            },
        ),
        migrations.AddField(
            model_name='member',
            name='idperson',
            field=models.ForeignKey(db_column='idperson', on_delete=django.db.models.deletion.CASCADE, to='association.person'),
        ),
        migrations.AddField(
            model_name='member',
            name='idtypemember',
            field=models.ForeignKey(db_column='idtypemember', on_delete=django.db.models.deletion.CASCADE, to='association.typemember'),
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('title', models.CharField(blank=True, max_length=100, null=True)),
                ('idtype', models.ForeignKey(blank=True, db_column='idtype', null=True, on_delete=django.db.models.deletion.CASCADE, to='association.imagetype')),
            ],
            options={
                'db_table': 'image',
                'managed': True,
            },
        ),
    ]
