# Generated by Django 4.0.6 on 2022-11-29 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('association', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='pdf',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
