# Generated by Django 4.0.6 on 2022-08-30 09:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('association', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Degree',
            fields=[
                ('id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'degree',
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'post',
            },
        ),
        migrations.AlterModelOptions(
            name='imagetype',
            options={},
        ),
        migrations.CreateModel(
            name='Studentdegree',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(blank=True, null=True)),
                ('subject', models.CharField(blank=True, max_length=255, null=True)),
                ('mention', models.CharField(blank=True, max_length=100, null=True)),
                ('iddegree', models.ForeignKey(db_column='iddegree', on_delete=django.db.models.deletion.DO_NOTHING, to='association.degree')),
                ('idmember', models.ForeignKey(db_column='idmember', on_delete=django.db.models.deletion.DO_NOTHING, to='association.member')),
            ],
            options={
                'db_table': 'studentdegree',
            },
        ),
        migrations.CreateModel(
            name='Memberpostinst',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('iddept', models.ForeignKey(blank=True, db_column='iddept', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='association.department')),
                ('idinst', models.ForeignKey(blank=True, db_column='idinst', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='association.institution')),
                ('idmember', models.ForeignKey(db_column='idmember', on_delete=django.db.models.deletion.DO_NOTHING, to='association.member')),
                ('idpost', models.ForeignKey(blank=True, db_column='idpost', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='association.post')),
            ],
            options={
                'db_table': 'memberpostinst',
            },
        ),
    ]
