# Generated by Django 4.0.6 on 2022-07-27 07:39

from django.db import migrations, models
import parler.models


class Migration(migrations.Migration):

    dependencies = [
        ('association', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MemberviewpostsTranslation',
            fields=[
                ('language_code', models.CharField(db_index=True, max_length=15, verbose_name='Language')),
                ('id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, max_length=10, null=True)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('username', models.CharField(blank=True, max_length=200, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('mail', models.CharField(blank=True, max_length=100, null=True)),
                ('posts', models.TextField(blank=True, null=True)),
                ('idtypemember', models.IntegerField(blank=True, null=True)),
                ('range', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'memberviewposts Translation',
                'db_table': 'memberviewposts_translation',
                'db_tablespace': '',
                'managed': False,
                'default_permissions': (),
            },
            bases=(parler.models.TranslatedFieldsModel, models.Model),
        ),
    ]
