# Generated by Django 4.0.6 on 2022-09-05 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('association', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='idimage',
        ),
        migrations.AddField(
            model_name='member',
            name='image',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
