# Generated by Django 4.0.6 on 2022-09-22 14:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('association', '0002_remove_member_idimage_member_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='idtype',
            field=models.ForeignKey(blank=True, db_column='idtype', null=True, on_delete=django.db.models.deletion.CASCADE, to='association.imagetype'),
        ),
        migrations.AlterField(
            model_name='member',
            name='idperson',
            field=models.ForeignKey(db_column='idperson', on_delete=django.db.models.deletion.CASCADE, to='association.person'),
        ),
        migrations.AlterField(
            model_name='member',
            name='idtypemember',
            field=models.ForeignKey(db_column='idtypemember', on_delete=django.db.models.deletion.CASCADE, to='association.typemember'),
        ),
        migrations.AlterField(
            model_name='memberpostinst',
            name='iddept',
            field=models.ForeignKey(blank=True, db_column='iddept', null=True, on_delete=django.db.models.deletion.CASCADE, to='association.department'),
        ),
        migrations.AlterField(
            model_name='memberpostinst',
            name='idinst',
            field=models.ForeignKey(blank=True, db_column='idinst', null=True, on_delete=django.db.models.deletion.CASCADE, to='association.institution'),
        ),
        migrations.AlterField(
            model_name='memberpostinst',
            name='idmember',
            field=models.ForeignKey(db_column='idmember', on_delete=django.db.models.deletion.CASCADE, to='association.member'),
        ),
        migrations.AlterField(
            model_name='memberpostinst',
            name='idpost',
            field=models.ForeignKey(blank=True, db_column='idpost', null=True, on_delete=django.db.models.deletion.CASCADE, to='association.post'),
        ),
        migrations.AlterField(
            model_name='messageofyear',
            name='idmember',
            field=models.ForeignKey(blank=True, db_column='idmember', null=True, on_delete=django.db.models.deletion.CASCADE, to='association.member'),
        ),
        migrations.AlterField(
            model_name='partner',
            name='idinst',
            field=models.ForeignKey(db_column='idinst', on_delete=django.db.models.deletion.CASCADE, to='association.institution'),
        ),
        migrations.AlterField(
            model_name='studentdegree',
            name='iddegree',
            field=models.ForeignKey(db_column='iddegree', on_delete=django.db.models.deletion.CASCADE, to='association.degree'),
        ),
        migrations.AlterField(
            model_name='studentdegree',
            name='idmember',
            field=models.ForeignKey(db_column='idmember', on_delete=django.db.models.deletion.CASCADE, to='association.member'),
        ),
    ]
