
# Generated by Django 4.0.6 on 2022-08-24 11:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('association', '0002_memberviewpoststranslation'),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'department',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('title', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'image',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Imagetype',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'imagetype',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Partner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True, null=True)),
                ('link', models.CharField(blank=True, max_length=150, null=True)),
                ('logo', models.CharField(blank=True, max_length=150, null=True)),
            ],
            options={
                'db_table': 'partner',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('username', models.CharField(blank=True, max_length=200, null=True)),
                ('title', models.CharField(blank=True, max_length=10, null=True)),
            ],
            options={
                'db_table': 'person',
            },
        ),
        migrations.RemoveField(
            model_name='memberpostinst',
            name='idinst',
        ),
        migrations.RemoveField(
            model_name='memberpostinst',
            name='idmember',
        ),
        migrations.RemoveField(
            model_name='memberpostinst',
            name='idpost',
        ),
        migrations.RemoveField(
            model_name='studentdegree',
            name='iddegree',
        ),
        migrations.RemoveField(
            model_name='studentdegree',
            name='idmember',
        ),
        migrations.DeleteModel(
            name='MemberviewpostsTranslation',
        ),
        migrations.AlterModelOptions(
            name='institution',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='member',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='messageofyear',
            options={'managed': True},
        ),
        migrations.RenameField(
            model_name='typemember',
            old_name='name',
            new_name='type',
        ),
        migrations.RemoveField(
            model_name='member',
            name='image',
        ),
        migrations.RemoveField(
            model_name='member',
            name='name',
        ),
        migrations.RemoveField(
            model_name='member',
            name='range',
        ),
        migrations.RemoveField(
            model_name='member',
            name='title',
        ),
        migrations.RemoveField(
            model_name='member',
            name='username',
        ),
        migrations.RemoveField(
            model_name='typemember',
            name='image',
        ),
        migrations.AddField(
            model_name='member',
            name='idimage',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='member',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.DeleteModel(
            name='Degree',
        ),
        migrations.DeleteModel(
            name='Memberpostinst',
        ),
        migrations.DeleteModel(
            name='Post',
        ),
        migrations.DeleteModel(
            name='Studentdegree',
        ),
        migrations.AddField(
            model_name='partner',
            name='idinst',
            field=models.ForeignKey(db_column='idinst', on_delete=django.db.models.deletion.DO_NOTHING, to='association.institution'),
        ),
        migrations.AddField(
            model_name='image',
            name='idtype',
            field=models.ForeignKey(blank=True, db_column='idtype', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='association.imagetype'),
        ),
        migrations.AddField(
            model_name='member',
            name='idperson',
            field=models.ForeignKey(db_column='idperson', default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='association.person'),
            preserve_default=False,
        ),
    ]
