# Generated by Django 4.0.6 on 2022-09-23 08:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('association', '0004_delete_memberviewposts'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentdegree',
            name='iddegree',
        ),
        migrations.RemoveField(
            model_name='studentdegree',
            name='idmember',
        ),
        migrations.DeleteModel(
            name='Degree',
        ),
        migrations.DeleteModel(
            name='Studentdegree',
        ),
    ]
