# Generated by Django 4.0.6 on 2022-09-23 11:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('association', '0006_link'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Link',
        ),
    ]
