# Generated by Django 4.0.6 on 2022-09-23 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('association', '0007_delete_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='partner',
            name='isLink',
            field=models.BooleanField(default=False),
        ),
    ]
