# Generated by Django 4.0.6 on 2022-09-27 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('association', '0008_partner_islink'),
    ]

    operations = [
        migrations.AddField(
            model_name='typemember',
            name='image',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
