# Generated by Django 4.0.6 on 2022-10-05 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('association', '0009_typemember_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='typemember',
            name='type',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
