# Generated by Django 4.0.6 on 2022-10-26 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('association', '0010_alter_typemember_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='messageofyear',
            name='description_en',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='messageofyear',
            name='description_fr',
            field=models.TextField(blank=True, null=True),
        ),
    ]
