# Generated by Django 4.2.1 on 2023-11-07 18:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('association', '0010_alter_typemember_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='typemember',
            name='image',
        ),
    ]
