# Generated by Django 4.0.6 on 2022-10-26 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('association', '0011_messageofyear_description_en_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='description_en',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='member',
            name='description_fr',
            field=models.TextField(blank=True, null=True),
        ),
    ]
