# Generated by Django 4.0.6 on 2022-10-26 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('association', '0012_member_description_en_member_description_fr'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagetype',
            name='type_en',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='imagetype',
            name='type_fr',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='partner',
            name='description_en',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='partner',
            name='description_fr',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='name_en',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='name_fr',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='typemember',
            name='description_en',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='typemember',
            name='description_fr',
            field=models.TextField(blank=True, null=True),
        ),
    ]
