# Generated by Django 4.0.6 on 2022-10-26 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('association', '0013_imagetype_type_en_imagetype_type_fr_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='typemember',
            name='type_en',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='typemember',
            name='type_fr',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
