# Generated by Django 4.0.6 on 2022-10-31 13:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('association', '0014_typemember_type_en_typemember_type_fr'),
    ]

    operations = [
        migrations.RunSQL(
            'ALTER SEQUENCE typemember_id_seq RESTART WITH 5;'
        )
    ]
