# Generated by Django 4.0.6 on 2022-11-02 05:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('association', '0014_typemember_type_en_typemember_type_fr'),
    ]

    operations = [
        migrations.CreateModel(
            name='Typememberimage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.CharField(blank=True, max_length=255, null=True)),
                ('idtypemember', models.ForeignKey(db_column='idtypemember', on_delete=django.db.models.deletion.CASCADE, to='association.typemember')),
            ],
            options={
                'db_table': 'typememberimage',
            },
        ),
    ]
