# Generated by Django 4.0.6 on 2022-11-02 06:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('association', '0016_typememberimage'),
    ]

    operations = [
        migrations.RunSQL(
            'ALTER SEQUENCE typememberimage_id_seq RESTART WITH 11;'
        )
    ]
