# Generated by Django 4.0.6 on 2022-11-02 19:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('association', '0016_typememberimage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='typemember',
            name='image',
        ),
    ]
