# Generated by Django 4.0.6 on 2022-11-29 06:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('association', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Publication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('description_en', models.TextField(blank=True, null=True)),
                ('description_fr', models.TextField(blank=True, null=True)),
                ('date', models.DateField(blank=True, null=True)),
                ('imagefront', models.CharField(blank=True, max_length=255, null=True)),
                ('imageback', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'publication',
            },
        ),
        migrations.CreateModel(
            name='Typepublication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('type_en', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('type_fr', models.CharField(blank=True, max_length=100, null=True, unique=True)),
            ],
            options={
                'db_table': 'typepublication',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Publicationdetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('pdf', models.CharField(blank=True, max_length=100, null=True)),
                ('idpublication', models.ForeignKey(db_column='idpublication', on_delete=django.db.models.deletion.CASCADE, to='publications.publication')),
            ],
            options={
                'db_table': 'publicationdetail',
            },
        ),
        migrations.CreateModel(
            name='Publicationauthor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idperson', models.ForeignKey(blank=True, db_column='idperson', null=True, on_delete=django.db.models.deletion.CASCADE, to='association.person')),
                ('idpublication', models.ForeignKey(db_column='idpublication', on_delete=django.db.models.deletion.CASCADE, to='publications.publication')),
            ],
            options={
                'db_table': 'publicationauthor',
            },
        ),
        migrations.AddField(
            model_name='publication',
            name='idtype',
            field=models.ForeignKey(db_column='idtype', on_delete=django.db.models.deletion.CASCADE, to='publications.typepublication'),
        ),
    ]
