# Generated by Django 4.0.6 on 2022-09-05 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='publication',
            name='idimageback',
        ),
        migrations.RemoveField(
            model_name='publication',
            name='idimagefront',
        ),
        migrations.AddField(
            model_name='publication',
            name='imageback',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='publication',
            name='imagefront',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
