# Generated by Django 4.0.6 on 2022-08-30 09:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('association', '0002_degree_post_alter_imagetype_options_studentdegree_and_more'),
        ('publications', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='publicationauthor',
            options={},
        ),
        migrations.AlterModelOptions(
            name='publicationdetail',
            options={},
        ),
        migrations.AlterField(
            model_name='publication',
            name='idimageback',
            field=models.ForeignKey(db_column='idimageback', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='idimageback', to='association.image'),
        ),
        migrations.AlterField(
            model_name='publication',
            name='idimagefront',
            field=models.ForeignKey(db_column='idimagefront', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='idimagefront', to='association.image'),
        ),
    ]
