# Generated by Django 4.0.6 on 2022-10-11 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0003_alter_publication_idtype_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='typepublication',
            name='type',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
