# Generated by Django 4.0.6 on 2022-10-27 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0004_alter_typepublication_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='publication',
            name='description_en',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='publication',
            name='description_fr',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='typepublication',
            name='type_en',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='typepublication',
            name='type_fr',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
