# Generated by Django 4.0.6 on 2022-10-31 11:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0005_publication_description_en_and_more'),
    ]

   
    operations = [
        migrations.RunSQL(
            'ALTER SEQUENCE typepublication_id_seq RESTART WITH 4;'
        )
    ]
